version: 0.2

phases: 
    install:
        commands:
            - echo "installing something"
    build:
        commands:
            - echo "start pip install"
            - pip install -r requirements.txt
